### ISSUE TITLE
olevba path not found: /usr/bin/olevba3

### ISSUE THREAD

**Issue by eilandert** [a16bitsysop/docker-olefy#8]
Hello, I just looked in my logs and see the docker a16bitsysop/olefy restarting the whole time.
Any idea how to fix this?

 olefy[3732316]: $OLEFY_BINDPORT=
 olefy[3732316]: $OLEFY_TMPDIR=
 olefy[3732316]: $OLEFY_LOGLVL=
 olefy[3732316]: $OLEFY_MINLENGTH=
 olefy[3732316]: $OLEFY_DEL_TMP=
 olefy[3732316]: $OLEFY_DEL_TMP_FAILED=
 olefy[3732316]: #033[1;32m $TIMEZONE=
 olefy[3732316]: #033[1;33m Starting olefy at 06/21/21 22:09:09 #033[0m
 olefy[3732316]: Changing to user olefy
 olefy[3732316]: olefy INFO <module> olefy listen address: ['0.0.0.0'] (type: <class 'list'>)
 olefy[3732316]: olefy INFO <module> olefy listen port: 10050
 olefy[3732316]: olefy INFO <module> olefy tmp dir: /tmp
 olefy[3732316]: olefy INFO <module> olefy python path: /usr/bin/python3
 olefy[3732316]: olefy INFO <module> olefy olvba path: /usr/bin/olevba3
 olefy[3732316]: olefy INFO <module> olefy log level: 20
 olefy[3732316]: olefy INFO <module> olefy min file length: 500
 olefy[3732316]: olefy INFO <module> olefy delete tmp file: 1
 olefy[3732316]: olefy INFO <module> olefy delete tmp file when failed: 1
 olefy[3732316]: olefy CRITICAL <module> olevba path not found: /usr/bin/olevba3

**Comment by a16bitsysop** [comment]
It looks like the name has changed in the new version to /usr/bin/olevba

I have changed it now if you pull a new image or make a new image.

Thanks for spotting it.

**Comment by eilandert** [comment]
watchtower already pulled a new one. seems to work!  thanks for the quick response 

olefy[3732316]: olefy INFO <module> serving on ('0.0.0.0', 10050)
